# Dockerfile for Blazor Server App

# Init
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

# Corelibs.Cognito
WORKDIR /src
COPY ["Corelibs.Cognito/Corelibs.Cognito/Corelibs.Cognito/Corelibs.Cognito.csproj", "Corelibs.Cognito/"]
RUN dotnet restore "Corelibs.Cognito/Corelibs.Cognito.csproj"
COPY ["Corelibs.Cognito/Corelibs.Cognito", "." ]
WORKDIR "/src/Corelibs.Cognito"
RUN dotnet build "Corelibs.Cognito.csproj" -c Release -o /app/build

# Corelibs.Blazor.UIComponents
WORKDIR /src
COPY ["Corelibs.Blazor.UIComponents/src/Corelibs.Blazor.UIComponents/Corelibs.Blazor.UIComponents.csproj", "Corelibs.Blazor.UIComponents/"]
RUN dotnet restore "Corelibs.Blazor.UIComponents/Corelibs.Blazor.UIComponents.csproj"
COPY ["Corelibs.Blazor.UIComponents/src", "." ]
WORKDIR "/src/Corelibs.Blazor.UIComponents/"
RUN dotnet build "Corelibs.Blazor.UIComponents.csproj" -c Release -o /app/build

# MyApp.UI.Common
WORKDIR /src
COPY ["blazor-app-template/src/MyApp.UI.Common/MyApp.UI.Common.csproj", "MyApp.UI.Common/"]
RUN dotnet restore "MyApp.UI.Common/MyApp.UI.Common.csproj"
COPY ["blazor-app-template/src", "." ]
WORKDIR "/src/MyApp.UI.Common/"
RUN dotnet build "MyApp.UI.Common.csproj" -c Release -o /app/build

# MyApp.UI.Server
WORKDIR /src
COPY ["blazor-app-template/src/MyApp.UI.Server/MyApp.UI.Server.csproj", "MyApp.UI.Server/"]
RUN dotnet restore "MyApp.UI.Server/MyApp.UI.Server.csproj"
COPY ["blazor-app-template/src", "." ]
WORKDIR "/src/MyApp.UI.Server/"
RUN dotnet build "MyApp.UI.Server.csproj" -c Release -o /app/build

# Final
FROM build AS publish
RUN dotnet publish "MyApp.UI.Server.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyApp.UI.Server.dll"]
