# Init
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

# MyApp.UI.Common
WORKDIR /src
COPY ["MyApp.UI.Common/MyApp.UI.Common.csproj", "MyApp.UI.Common/"]
RUN dotnet restore "MyApp.UI.Common/MyApp.UI.Common.csproj"
COPY . .
WORKDIR "/src/MyApp.UI.Common/"
RUN dotnet build "MyApp.UI.Common.csproj" -c Release -o /app/build

# MyApp.UI.Server
WORKDIR /src
COPY ["MyApp.UI.Server/MyApp.UI.Server.csproj", "MyApp.UI.Server/"]
RUN dotnet restore "MyApp.UI.Server/MyApp.UI.Server.csproj"
COPY . .
WORKDIR "/src/MyApp.UI.Server/"
RUN dotnet build "MyApp.UI.Server.csproj" -c Release -o /app/build

# Final
FROM build AS publish
RUN dotnet publish "MyApp.UI.Server.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyApp.UI.Server.dll"]
